### ISSUE TITLE
NotImplementedError: all_exhausted stopping strategy in `interleave_datasets` is not implemented yet with a list of <class 'datasets.iterable_dataset.IterableDataset'>.

### ISSUE THREAD

**Issue by zwhe99** [fe1ixxu/ALMA#15]
`bash runs/mono_ft.sh tmp` yields the following error:

```shell
Traceback (most recent call last):
  File "/timurhe/ALMA/run_llmmt.py", line 223, in <module>
    main()
  File "/timurhe/ALMA/run_llmmt.py", line 131, in main
    train_raw_data = interleave_datasets(train_raw_data, probabilities=interleave_probs, seed=training_args.seed, stopping_strategy="all_exhausted")
  File "/data/anaconda3/envs/alma/lib/python3.9/site-packages/datasets/combine.py", line 123, in interleave_datasets
    raise NotImplementedError(
NotImplementedError: all_exhausted stopping strategy in `interleave_datasets` is not implemented yet with a list of <class 'datasets.iterable_dataset.IterableDataset'>.
```

**Comment by fe1ixxu** [comment]
Thank you for your interest in our work!

It seems like the issue is with the `datasets` package. Could you please share the versions of your `transformers` and `datasets`? Ensure that your transformers version is `4.30.dev` (you can revert to this version by running `pip install git+https://github.com/fe1ixxu/ALMA.git@hf-install`).

My `datasets` version is `2.14.7`. Running `mono_ft.sh` works for me.

**Comment by zwhe99** [comment]
`datasets==2.14.6` works for me.
